# site settings
title: Yash Gajaria
subtitle: 
email: ygajaria@uwaterloo.ca
description: 1B SYDE @UWaterloo
baseurl:  # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: Toronto
state: 
zip_code: 
country: Canada
phone: (647) 937 3138

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/yashgajaria
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/yashgajaria/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
